### ISSUE TITLE
Filter out Whimsical weather

### ISSUE THREAD

**Issue by darkanx** [stormytuna/HellWeather#1]
Can you filter out the Whimsical weather from this mod: https://thunderstore.io/c/lethal-company/p/Bobbie/WhimsicalWeather/

Perhaps limit it to the default weathers, just so future modded weathers do not interfere.

**Comment by stormytuna** [comment]
Closing as complete in [2bb1f42](https://github.com/stormytuna/HellWeather/commit/2bb1f4212a7afb233c68b6f40fefa6717fe8a6ea)
