### ISSUE TITLE
Softlocking on custom moons

### ISSUE THREAD

**Issue by X3n0nP0w3r3d** [stormytuna/HellWeather#3]
Getting softlocked on custom moons with always hell weather enabled.

![image](https://github.com/stormytuna/HellWeather/assets/38383491/dd1aeef2-d59c-4ec6-bbb5-e0132ee984ce)

`[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
HellWeather.Patches.CurrentWeatherVariablePatches.SetupCurrentWeatherVariables (RoundManager __instance) (at <637b5c54c07649b4a53cbea5dbab9c0f>:IL_001D)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::SetToCurrentLevelWeather>(RoundManager)
RoundManager.FinishGeneratingLevel () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0027)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager,int,int)
RoundManager+<LoadNewLevelWait>d__115.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0076)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)`

**Comment by stormytuna** [comment]
Closing as fixed in 0b09ec8c6bf67482478a35c477ee7e448ae646c0
